blocklist:
  - SPAWNER
  - AIR
  - BED
  - MAP
  - BOW
  - AXE
  - HOE
  - SIGN
  - BOAT
  - BOOK
  - BOOTS
  - SWORD
  - BANNER
  - BUCKET
  - HELMET
  - SHOVEL
  - POTION
  - PICKAXE
  - A_STICK
  - MINECART
  - LEGGINGS
  - CHESTPLATE
  - SHULKER_BOX
  - HORSE_ARMOR
  - BANNER_PATTERN
  - MUSIC_DISC
  - FISHING_ROD
  - FLINT_AND_STEEL
  - RABBIT_STEW
  - BEETROOT_SOUP
  - MUSHROOM_STEW
  - SUSPICIOUS_STEW
  - HONEY_BOTTLE
  - CAKE
  - ARMOR_STAND
  - TRIDENT
  - SADDLE
  - ELYTRA
  - EGG
  - ENDER_PEARL
  - FIREWORK_ROCKET
  - SHEARS
  - SHIELD
  - TOTEM_OF_UNDYING


#このブロックリストはアイテムに指定の単語が入っている場合弾かれます。