name: Storage
version: ${project.version}
main: masa3mc.storage.Storage
api-version: 1.20
softdepend: [Vault]
depend: [Vault]
commands:
  storage:
    usage: /storage
    description: Open Storage GUI
  st:
    usage: /st
    description: Open Storage GUI
  addstorage:
    usage: /addstorage
    description: add Storage item
  ast:
    usage: /ast
    description: add Storage item
  locstorage:
    usage: /locstorage
    description: chencge
  lst:
    usage: /lst
    description: chencge